;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/MarkdownEditor
DestinationPath=Content/Localization/MarkdownEditor
ManifestName=MarkdownEditor.manifest
ArchiveName=MarkdownEditor.archive
ResourceName=MarkdownEditor.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=ja

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

