;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/MarkdownEditor
DestinationPath=Content/Localization/MarkdownEditor
ManifestName=MarkdownEditor.manifest
ArchiveName=MarkdownEditor.archive
CulturesToGenerate=en
CulturesToGenerate=ja

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=MarkdownEditor.csv

